// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changetype_members : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetype_members));
        
        string IMigrationMetadata.Id
        {
            get { return "202201221837518_change-type_members"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
