// <auto-generated />
namespace LibraryManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class isReturned_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isReturned_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202201230723563_isReturned_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
